### ISSUE TITLE
Support of new versions of WebApi

### ISSUE THREAD

**Issue by martinsubash** [JakeGinnivan/WebApi.Hal#100]
I have used the following dll's versions in my project. With this versions i am not able to install WebApi.Hal from Nuget packages.

System.Net.Http.Formatting 5.2.3.0 - (Microsoft.AspNet.WebApi.Client.5.2.3)
System.Web.Http 5.2.3.0 - (Microsoft.AspNet.WebApi.Core.5.2.3)
System.Web.Http.WebHost 5.2.2.0 - (Microsoft.AspNet.WebApi.WebHost.5.2.2)
Newtonsoft.Json 6.0.0.0

These having dependency constraint with WebApi.Hal. Because WebApi.Hal using the lower version of the above dll's. Kindly reply with possible solution for this.

Thanks

**Comment by panmanphil** [comment]
Sorry, on my way to work, but check in the other answers here, I think this has a simple solution

**Comment by martinsubash** [comment]
Hi,
     To more clarity about the issue I have enclosed the issue. Installation getting failed when I am trying to install the nuget package "install-package webapi.hal"  in Web API-2.

Query:

           Is it possible to release the HAL package with the latest version of supporting dll's refered?

As a workaround, we are downloading the source code and referred the latest version of supporting dlls to make the HAL works.

Provide your suggestions.

![hal dependency dll issue](https://cloud.githubusercontent.com/assets/7115492/7675662/c0a3e772-fd58-11e4-85ac-14a2fa913da6.png)

**Comment by critchie** [comment]
Voting this one up...  it needs a little love.

**Comment by panmanphil** [comment]
closing stale issue
