### ISSUE TITLE
nullable embedded lists

### ISSUE THREAD

**Issue by kbrichan** [JakeGinnivan/WebApi.Hal#101]
Currently for an embedded list, an empty list must be instantiated in the constructor. I probably created this requirement some time ago, but a) it seems like an unnecessary requirement considering an ordinary Json converter knows how to instantiate a list for you if not already instantiated, and b) we have a use case needing to distinguish on the server side between an empty embedded list vs. a null list, meaning distinguishing whether the hal+json payload had an embedded list present or absent.

An empty list could not be used as the distinguisher because our WebApi.Hal implementation required an empty list to be instantiated in the constructor in order for the internals to hang together without blowing up.

I have a proposed fix, for which I'll do a pull request.

**Comment by kbrichan** [comment]
Hey @JakeGinnivan, I tried publishing this fix to NuGet but it failed:
[23:39:42]Step 1/1: NuGet Publish (4s)
[23:39:46][Step 1/1] Step NuGet Publish failed

Any ideas?

**Comment by JakeGinnivan** [comment]
Will check out when I get home

Sent from my Windows Phone
________________________________

**Comment by kbrichan** [comment]
Thanks, apparently there's a loose nut behind my keyboard. I tried setting the build version to 2.5.1 so it wouldn't conflict with the 2.5.0 already out on nuget, but it didn't carry forward through to the nuget publish. There is some magic sauce I'm ignorant of.

**Comment by JakeGinnivan** [comment]
I think this is the issue:

![image](https://cloud.githubusercontent.com/assets/453152/7841818/41d9ca1a-0497-11e5-8413-806f595991c0.png)

The old nuget file was sitting around so it was trying to reupload it

**Comment by JakeGinnivan** [comment]
Ugh, screenshots on high dpi screens is terrible
