### ISSUE TITLE
Length attribute on Link for rel="enclosure"

### ISSUE THREAD

**Issue by mkamonster** [JakeGinnivan/WebApi.Hal#104]
When making use of the Link with a rel="enclosure" we should be able to include a length attribute. According to: http://tools.ietf.org/html/rfc4287#page-22

Can this be added?

**Comment by panmanphil** [comment]
length is not a HAL defined property though. Are you thinking some sort of customization technique that would allow for it?

**Comment by mkamonster** [comment]
Interesting I didn't read the Hal specs in that detail. I was looking at relevant rel-names. We are making use of a rel="enclosure" where we specify the media-type and we read the suggestion to also add the length attribute.

This seems not in line with the Hal specification. Eventualy a customization technique like allowing a dictionary for additional properties on a Link could be something.

**Comment by panmanphil** [comment]
closing stale issue
