### ISSUE TITLE
Hosting on platforms other than IIS?

### ISSUE THREAD

**Issue by johnnysaucepn** [JakeGinnivan/WebApi.Hal#107]
The current NuGet package depends on the full-blown Microsoft.AspNet.WebApi package, containing all the IIS-hosting-specific code. As far as I can see, the main WebApi.Hal assembly only really needs the use of Microsoft.AspNet.WebApi.Client (for formatting) - the IIS components only appear to be used for the full example application.

This makes it less lightweight for including in projects that, for example, use the Owin interface, whether self-hosted or not. In some cases, it's just inconvenient extra dependencies, but it also creates some package conflicts.

Can someone confirm that I'm right in saying this? Is it easy to change the NuGet package dependencies?

**Comment by panmanphil** [comment]
I think you are definitely correct in saying this. I may actually have some time to apply to this in the next week or few, but if you want to give it a try, please do. I remember giving a short try more than a year back, and there were just enough things to consider that I stopped short at the time.

**Comment by johnnysaucepn** [comment]
I will give it a try - I'm new to Git, Github and even creating nuget packages, so be gentle!
I forked and removed the relevant dependencies last night, unit tests all pass so I'll submit a pull request and let the more knowledgeable people spot the pitfalls.

**Comment by JakeGinnivan** [comment]
If you get stuck with the git stuff just ask, happy to help

**Comment by johnnysaucepn** [comment]
Assuming this does work, what effect would this change have on those upgrading the package from nuget?
