### ISSUE TITLE
NUGET-package: Strict reference to Microsoft.AspNet.WebApi v5.1.2

### ISSUE THREAD

**Issue by wendelborg** [JakeGinnivan/WebApi.Hal#109]
Got an issue adding WebApi.Hal to a project due to a very strict reference to WebApi version 5.1.2 (had 5.2.3 installed). From the .nuspec-file: 

``` xml
<dependencies>
     <dependency id="Microsoft.AspNet.WebApi" version="5.1.2" />
</dependencies>
```

Worked around it by first removing Microsoft.AspNet.WebApi and everything referencing it, then installed WebApi.Hal, and lastly reinstalled and upgraded everything referenced in the first place.

Loosening up the restrictions could possibly be helpful for others, can this be done?

**Comment by panmanphil** [comment]
closing stale issue
