### ISSUE TITLE
Cannot self host with katana

### ISSUE THREAD

**Issue by jabbera** [JakeGinnivan/WebApi.Hal#113]
The dependency on Microsoft.AspNet.WebApi means that we cannot self host with owin\katana. Sad panda. Can the dependency be changed to be on Core and Client instead?

**Comment by jabbera** [comment]
Actually there is a pull request for this already!

https://github.com/JakeGinnivan/WebApi.Hal/pull/108

**Comment by wis3guy** [comment]
solved in the latest stable version
