### ISSUE TITLE
Link.CreateUri does not work with arrays

### ISSUE THREAD

**Issue by AndreasKorn** [JakeGinnivan/WebApi.Hal#115]
Passing a string array (IEnumerable<string>) as one item in the "parameters" argument to "Link.CreateUri(params object[] parameters)" does not work (although the underlying UriTemplate class supports it in its parameters list).
This is needed when constructing urls for web.api which can contain arrays in the query part (the same query parameter occuring multiple times, e.g. http://myhost/with/some/path?tag=bla&tag=blub).

In Link.SubstituteParams all values are converted to strings with ToString() so all arrays are converted to single values (e.g. "System.String[]").

Enumerables should be passed as Enumerables to the UriTemplate class (and only the items converted to strings where necessary).

The same happens with Dictionaries (UriTemplate supports IDictionary<string,string>).

**Comment by wis3guy** [comment]
Please create a pull request for this

**Comment by panmanphil** [comment]
closing stale issue
