### ISSUE TITLE
Link.Rel isare always set to lower case

### ISSUE THREAD

**Issue by edwardginhands** [JakeGinnivan/WebApi.Hal#116]
When creating a link the Rel property is always set to lower case. This prevents the use of camel case in the response. The RFC states that it should be case insensitive for comparison but that shouldn't prevent the user from being able to set the Rel property to whichever case they want.

**Comment by wis3guy** [comment]
I agree that those two things are not the same but at the same time wonder why you, then, are so adement about camel-casing your `rel` attributes. If, to a client it makes no difference, then why do you want the casing to be reflected during transport.

**Comment by edwardginhands** [comment]
For readability by the developer of the consuming client really rather than
client itself. It just makes it a bit easier to work with, but from a
client point of view I agree that when being consumed it should be case
insensitive.

**Comment by panmanphil** [comment]
closing stale issue
