### ISSUE TITLE
Support of Generic in Representation

### ISSUE THREAD

**Issue by vRITHNER** [JakeGinnivan/WebApi.Hal#117]
Hi,
It could be cool to support Generics in Representation (Representation<xxxxx>)
For some classes which need all properties, it could be cool to avoid to copy/paste them into the representation.
Thanks

**Comment by wis3guy** [comment]
I personally avoid the copy/paste-ing by creating a common base representation for my other representations. Would that not work in your situation? Perhaps you could paste a snippet to illustrate what your are trying to accomplish?

**Comment by panmanphil** [comment]
closing stale issue
