### ISSUE TITLE
Having latest code source

### ISSUE THREAD

**Issue by vRITHNER** [JakeGinnivan/WebApi.Hal#119]
Hello, I don't know if I make a mistake but I can't deserialize ResourceList (see but #103) when I tried the sample or my objects with the source code in GitHub.
When I tried using the latest Nuget version 2.6.0.0, it is working.
Does it mean latest modifications has not been commited  ? 
(version of the package after compilation == 2.0.0.0)
Thanks

**Comment by panmanphil** [comment]
closing stale issue
