### ISSUE TITLE
Adding Curies

### ISSUE THREAD

**Issue by Roonerelli** [JakeGinnivan/WebApi.Hal#121]
Do you have any examples of how to create curies using your API?

I can see there is an overload on the Link constructor that takes a CurieLink, but cant work out how to get them to render

I coulnd't see a good example in the samples or tests either

any pointers?

thanks v much

**Comment by wis3guy** [comment]
Have you checked: https://github.com/JakeGinnivan/WebApi.Hal/wiki/Hypermedia-configuration,-container-and-appenders

**Comment by Roonerelli** [comment]
thanks - I did look in the wiki but thought it was empty!

So is this to be done instead of having a static LinkTemplates file that defines the links?

**Comment by wis3guy** [comment]
No, not necessarily, but it does enable automatic CURIE generation. Alternatively, i think you could create a `CuriesLink` instance and add it manually by calling the `ToLink()` method on it.
