### ISSUE TITLE
HypermediaAppender - Controlling automatic link to embedded resource list

### ISSUE THREAD

**Issue by cuctc** [JakeGinnivan/WebApi.Hal#122]
With the introduction of the HypermediaAppender (which I really like btw), I see that in the method ProcessPropertyValue automatically adds a templated link for embedded resources. I personally see this as unnecessary since I'm generating the links that I want the consumer to follow and I don't provide Id's in my payload to allow the consumer to hack the url's from the templates. However, up until now, having this link present has been benign. I've encountered a scenario where this has become problematic and it would be nice to have a way to control if/when these links are generated. 

FWIW, the scenario in which it's an issue is when I have a resource that has a list of related resources of the same type. Here's an example:

```
{
"_links": {
    "self": {
        "href": "/cases/3233/relatedCases",
        "title": "Related Cases"
    },
    "case": [{
        "href": "/cases/3233",
        "title": "Case Details"
    },
    {
        "href": "/cases/{id}",
        "title": "Case Details",
        "templated": true
    }]
},
"_embedded": {
    "relatedcases": [{
        // properties removed from payload
        "_links": {
            "self": {
                "href": "/cases/3358",
                "title": "Case Details"
            }
        }
    }]
}
}
```

I explicitly add a link to the parent resource to enable easy navigation. In this example, it's the case link with an href of /cases/3233. The framework automatically adds the templated link below it, causing the case link to become a json collection rather than a single property. While that is legal/valid for HAL links, it's not what I want nor what any of my other resources provide in this sort of context. 

Could we look into ways of overriding the default behavior of automatically adding these links?

**Comment by wis3guy** [comment]
@cuctc I feel that the problem here is the fact that you configured the `case` link *and* added one manually. What appender do you use? Could you share your configuration and custom appender code?

**Comment by panmanphil** [comment]
closing stale issue
