### ISSUE TITLE
Link objects different from RFC 

### ISSUE THREAD

**Issue by NunoJP** [JakeGinnivan/WebApi.Hal#124]
I created an object that extends the Representation class, when adding a link to it the JSON generated does not generate an object with the name of the relation and the href inside, it generates something like this:

```
{
   id: 5,  
   name: "project5",
 _links: [
   {
       rel: "self",
       href: "/api/projects/5"
    }
  ]
}
```

It is different from the RFC, is the object meant to be this way?
thank you

**Comment by kbrichan** [comment]
What you are showing is the raw JSON content type, not the HAL type.
You need to specify the header "accept: application/hal+json" in your request to get the HAL content type.

**Comment by NunoJP** [comment]
Thank you. I had not configured the formater properly.

I now have another problem.

When I try to return an object that extends SimpleListRepresentation I get a null poiter exception that states "ResourceConverter.cs not found". 
When I return a single object that extends Representation:
~~~
{
id: 5,
name: "project5",
_links: {
prev: {
href: "/api/projects/4"
},
self: {
href: "/api/projects/5"
},
next: {
href: "/api/projects/6"
}
}
}
~~~
 I have no problems with the formater

**Comment by kbrichan** [comment]
The SimpleListRepresentation works with the sample project included with WebApi.Hal. The SimpleListRepresentation also works in our production usage of WebApi.Hal. I'm not sure what would generate the message "ResourceConverter.cs not found". Can you get the source code for WebApi.Hal and debug into it with your project to help us identify what is causing the problem?

**Comment by NunoJP** [comment]
I added the sources for debugging which "solved" the message "ResourceConverter.cs not found" problem.

 The actual exception came from Representation.ProcessPropertyValue, line 156: the Links object was null. 

When creating my MProjectListRepresentation (that extends SimpleListRepresentation) I didn't add any Links to the Links object, creating an empty Link list

In ResourceConverter.WriteJson lines 50 and 51 
~~~
if (!linksBackup.Any())
resource.Links = null;
~~~
as my list was empty it became null, I got the exception from it

I believe this was a bug caused by me, as I had not created a "self" link on the MProjectListRepresentation causing it to be empty
