### ISSUE TITLE
Halclient

### ISSUE THREAD

**Issue by xiongtec** [JakeGinnivan/WebApi.Hal#125]
Is there a client side implementation for response message to serialize back to representation?

**Comment by kbrichan** [comment]
yes. try this, where "response" is HttpResponseMessage and T is a representation-derived class:
var content = await response.Content.ReadAsStringAsync();
using (var stream = new MemoryStream(Encoding.UTF8.GetBytes(content))) {
    var result = (T)new JsonHalMediaTypeFormatter().ReadFromStream(typeof(T), stream, Encoding.UTF8, null);
}

**Comment by xiongtec** [comment]
Thank you.

**Comment by CarlosTorrecillas** [comment]
Really useful!
