### ISSUE TITLE
Title value is not replaced

### ISSUE THREAD

**Issue by LijoCheeran** [JakeGinnivan/WebApi.Hal#126]
We have following two constructors in Link class:

```
public Link(string rel, string href, CuriesLink curie)
public Link(string rel, string href, string title = null)
```

I used following to create link:

```
  foreach (Priority p in theTask.PossiblePriorities)
  {
       Links.Add(LinkTemplates.TaskLinks.PriorityLink.CreateLink(new { taskID = theTask.TaskID, 
                           priorityID = p.PriorityID, titleVal = "Test1" }));
  }
```

Following is my link template:

```
public static class LinkTemplates
    {

        public static class TaskLinks
        {
            public static Link TaskEntry { get { return new Link("self", "~/api/tasks/{taskID}"); } }
            public static Link PriorityLink 
            { 
                get 
                {
                    Link l = new Link("priorities",
                                                "~/api/tasks/{taskID}/priorities/{priorityID}",
                                                "{titleVal}");
                    return l;
                } 
            }
        }
    }
```

Following is the response. 

```
{
  "TaskID": 1,
  "TaskName": "Task1",
  "CurrentPriority": "Medium",
  "Category": "IT",
  "_links": {
    "self": {
      "href": "/api/tasks/1"
    },
    "priorities": [
      {
        "href": "/api/tasks/1/priorities/101",
        "title": "{titleVal}"
      },
      {
        "href": "/api/tasks/1/priorities/103",
        "title": "{titleVal}"
      },
      {
        "href": "/api/tasks/1/priorities/104",
        "title": "{titleVal}"
      }
    ]
  }
}
```

It is not replacing the title value. What am I missing here?

Thanks.

**Comment by kbrichan** [comment]
Only the href uses template substitution. Title is just a simple string. Set title directly to "Test1" in your example instead of "{titleVal}".

**Comment by LijoCheeran** [comment]
It won't meet my requirement. I need to display name property of each Priority object. So, are you suggesting me to write one Link proerty for each priority by hand - like "public static Link PriorityLinkLow", "public static Link PriorityLinkHigh", etc. What if I need a new priority in my domain? I need to break my code - isn't it? Do you consider it as a good design, for a library to be used in projects?

**Comment by kbrichan** [comment]
The CreateLink method is merely a convenience for cloning a prototype and substituting URI template parameters into the Href of the newly cloned Link object.

To set the Title property, clone your prototype Link via CreateLink, then set the Title property, such as (modifying your code from above slightly):

```
foreach (Priority p in theTask.PossiblePriorities)
{
    var lnk = LinkTemplates.TaskLinks.PriorityLink.CreateLink(
        new { taskID = theTask.TaskID, priorityID = p.PriorityID});
    lnk.Title = whateverYouWantTheTitleValueToBe;
    Links.Add(lnk);
}
```
