### ISSUE TITLE
Links of embedded resources are always listed twice

### ISSUE THREAD

**Issue by martijnburgers** [JakeGinnivan/WebApi.Hal#128]
A  `SimpleListRepresentation` with embedded resources can result in the followin JSON:

``` json
{
    "_embedded": {
        "feedback": [
            {
                "_links": {
                    "new_reply": {
                        "href": "/api/feedback/1/reply"
                    },
                    "self": {
                        "href": "/api/feedback/1"
                    }
                },
                "createDate": "2016-09-24T13:41:18.6187209",
                "id": 1,
                "subject": "This is a subject",
                "text": "This is some text",
                "username": "MARTIJN BURGERS"
            }
        ]
    },
    "_links": {
        "feedback": {
            "href": "/api/feedback/1"
        },
        "self": {
            "href": "/api/feedback"
        }
    }    
}
```

The link of feedback 1 is provided twice in `_links` and feedback `_links`. This is not really a problem with a small list of embedded resources but becomes one when this list is larger. 

I think it should be possible to not include embedded resource links in the root `_links`. I've looked into the source code to override this behavior but see no simple way to do so.

Would be helpful if more methods would be virtual. Making the `ToLink` method on `Representation` virtual would help me in this case.

**Comment by martinsubash** [comment]
I also have the same problem, for larger items it seems not readable and payload also high.

providing a option to enable/disable "_links" is required. 

```
 "_links": {
        "feedback": {
            "href": "/api/feedback/1"
        },
        "self": {
            "href": "/api/feedback"
        }
    }   
```

**Comment by kbrichan** [comment]
Perhaps you could submit a pull request. In the meantime, I've found using the newer HypermediaAppender reduces all the extra links to one templated link. You might investigate using the HypermediaAppender.
