### ISSUE TITLE
Question: Possibility to hide extra links ?

### ISSUE THREAD

**Issue by ghost** [JakeGinnivan/WebApi.Hal#130]
Whenever, I request for multiple items, it give me reponse like this:
![20-12-2016 05-46-37 pm](https://cloud.githubusercontent.com/assets/13468989/21359680/48d796a8-c6dd-11e6-96a3-be498eeeac3a.png)
Is there any possibly to hide the beers links from **_links**, which I have highlighted in the below image
![20-12-2016 05-46-37 pm](https://cloud.githubusercontent.com/assets/13468989/21359820/c03f7cec-c6dd-11e6-9938-a6ff1932d4c4.png)
I tried to search in the code but for this I have to changes in the WebAPI.Hal which i don't want to do, so is there any other way of doing it since I am using this API for the first time.

**Comment by kbrichan** [comment]
There is not a way to automatically hide links of embedded resources. However, if you use the newer capability of HypermediaAppender, the multiple embedded links are replaced with a single templated link.
