### ISSUE TITLE
Wrong URI encoding in CreateLink(string newRel, params object[] parameters)

### ISSUE THREAD

**Issue by kuehlmeyer** [JakeGinnivan/WebApi.Hal#132]
It seems that some special characters in URI template parameters are not encoded properly. Here's a code example:

    WebApi.Hal.Link templatedLink = new WebApi.Hal.Link("somerel", "http://localhost/{path}");
    WebApi.Hal.Link resolvedLink = templatedLink.CreateLink(new { path = "a / b c" });
    Assert.AreEqual("http://localhost/a%20%2F%20b%20c", resolvedLink.Href);

We expect that all special characters, including spaces, are percent encoded. However, the resulting Href is "http://localhost/a %2F b c". The slash is encoded properly, but the spaces are not. We think that this is because of this line of code in the Link class (Link.cs, line 102):

    clone.Href = CreateUri(parameters).ToString();

We had similar issues in our own code. The **Uri.ToString()** method returns a "canonical representation", but not really the actual URI. That is done by the member **AbsoluteUri**. In our opinion this line should read:

    clone.Href = CreateUri(parameters).AbsoluteUri;

**Comment by vsliouniaev** [comment]
Why not submit a pull request ;-)
