### ISSUE TITLE
The negotiation doesnt return hal+client when i use a [Route] in Web Api Controller.

### ISSUE THREAD

**Issue by Warsouler** [JakeGinnivan/WebApi.Hal#134]
If i call an Action with a simple Api request works fine. But when i use a Route decorator ex:
[Route("~/api/pepe/{id:int}/myitems")]

The response its only json and no hal+json.
I used the accept header content type but doesnt work.
Any idea?
Thanks!

**Comment by kbrichan** [comment]
When you say "a simple Api request works", by "simple" do you mean a URI whose controller method has no [Route]?

Our API works with or without [Route]. The [Route] attribute does not control media formatting. It only controls how to spell the URI and which controller method handles a request.

Your subject line mentions "hal+**client**", did you mean "application/hal+**json**"? You might want to check to make sure your header is:
accept: application/hal+json

**Comment by Warsouler** [comment]
Yes sorry for the title i meant hal+json.
I do not know what's happening.
What I noticed is that when I return a normal ApiController query, when it does not use the Route it enters the CreateHypermedia but when there is a route it does not enter that method.

I repeat: The methods with or without route enter perfectly, the problem when using route is that it returns a json without the format hal + json.

Thanks for the reply and the time

**Comment by kbrichan** [comment]
Hmmm. Weird.
We have not seen this problem in our API where media formatting is affected by [Route].

Try these:
1) On a working request, one without [Route], add the [Route] attribute and see if it now fails.
2) On the failing request, one with [Route], take off the [Route] attribute and see if it now works.

Of course you might have a different URI to get to each of those methods now, but let's see if we can determine whether it's really the presence or absence of [Route], or if it's something else.

**Comment by Warsouler** [comment]
Just try, and it's the route attribute that breaks the formatting to hal + json. I do not know how I could solve it: S.

**Comment by kbrichan** [comment]
Very weird. Just to make sure I understand:
1) you had a working request without [Route], you added [Route], and it now fails?
2) you had a different failing request with [Route], you removed [Route], and it now works?

**Comment by Warsouler** [comment]
Yes.
The format of the response fails, when I include the route, it returns JSON and when I do not include the route it returns hal + json

**Comment by kbrichan** [comment]
Could you please show us the code for your controller methods.

**Comment by Warsouler** [comment]
public class ProvincesController : ApiController
    {
        private IProvinceServices _services;
        public ProvincesController(IProvinceServices services)
        {
            _services = services;
        }

        public async Task<IHttpActionResult> GetProvinces(int page = 1,
        int top = 5, string orderby = nameof(ProvinceDTO.idprovince), string ascending = "asc")
        {
            var count = 0;
            var query = _services.GetAll(page, top, orderby, ascending, ref count).AsQueryable();
            var dtos = from a in query
                       select new ProvinceDTO()
                       {
                           country = a.country,
                           idprovince = a.idprovince,
                           name = a.name
                       };

            ProvinceDTOCollectionRepresentation dt = new ProvinceDTOCollectionRepresentation(dtos.ToList(),
              FilterHelper.GenerateFilter(top, orderby, ascending), page, count, top);

            return Ok(dt);

        }

        public async Task<IHttpActionResult> GetProvince(int id)
        {
            ProvinceBE province = _services.GetById(id);
            if (province == null)
            {
                return NotFound();
            }

            ProvinceDTO dto = new ProvinceDTO()
            {
                country = province.country,
                idprovince = province.idprovince,
                name = province.name,
            };
            dto.CreatesMySelfLinks();
            
            return Ok(dto);
        }

Works fine (without Route) Return Hal+Json (i test with MVCClient, Postman and Fiddler).




this doesnt work fine (return Json, and no enter to CreateHyperMedia)

 [Route("~/api/provinces/{id:int}/locations")]
        [HttpGet]
        public IHttpActionResult GetLocations(int id)
        {
            try
            {
                var a = Request;
                var r = RequestContext;
                var location = from b in _services.GetAllLocations(id).AsQueryable()
                               select new LocationDTO()
                               {
                                   idlocation = b.idlocation,
                                   name = b.name,
                               };
                int page = 1;
                int top = 100; string orderby = nameof(ProvinceDTO.idprovince); string ascending = "asc";
                LocationDTOCollectionRepresentation dt = new LocationDTOCollectionRepresentation(location.ToList(),
                FilterHelper.GenerateFilter(top, orderby, ascending), page, location.Count(), top);
                return Ok(dt);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }

If i try to put or remove the Route attribute the Formatter works.

**Comment by kbrichan** [comment]
Thanks. Let me make sure I understand.
1) with **no** [Route], GetLocations(int id) returns hal+json?
2) with **no** [Route], GetProvinces(...) returns hal+json?
3) **with** [Route], GetLocations(int id) **does not** return hal+json?
4) **with** [Route], GetProvinces(...) **does not** return hal+json?

**Comment by Warsouler** [comment]
Yes, it's as you say.
Any method with Route does not bring hal + json.
No route, bring perfect

**Comment by kbrichan** [comment]
This is an interesting puzzle. As I say, our API returns hal+json for both [Route] and no [Route].

Try this: enable XML media formatter by adding it to the list of formatters. Just to be certain, make sure your models support data contract and data member. Then see if application/xml works with no [Route] but fails (returns json) with [Route].

The major differences between our controller methods and yours are we are not using async and we are not returning IHttpActionResult. Instead, our controllers were built a while ago with the older mechanism of returning the Representation itself.

Perhaps there is a problem with .NET WebApi content negotiation in the IHttpActionResult or async.

If you can figure this out, it will help the rest of us if we convert to the newer async and IHttpActionResult.

**Comment by Warsouler** [comment]
With xml and with hal + xml it does the same to me.
The rarest thing is that on any side I have no formater enabled and I clean them to try. I do not know how to negotiate and get to json when I use route.
In addition also returning the representation, without using IHttpContext or async and it does not work either.

**Comment by kbrichan** [comment]
So the ordinary application/**xml** (I don't mean hal+xml) returns **xml** with **no** [Route], but the ordinary application/xml returns **json** with [Route]. Right?

If so, this means the problem is not the hal library. It is something else. If this is right, you should post this problem of "application/xml returning json" to a .NET WebApi forum to see if anyone knows why.

If you can get application/xml to return xml with [Route], then hal should return hal+json with [Route].
Keep us updated on what you find.

**Comment by Warsouler** [comment]
I find the solution.
I used Unity for dependency injections and was loading a new HttpConfig, when configuring that I would not pass the formatters to Unity. I only configured the formatters globally. When removing the unity began to work and then to put unity and debug I saw that the httpconfig that happened to him did not have the formatters. It seems that unity when mapping routes with the Route attribute searches within its configuration and if it does not find it it uses the default config. So solve it by adding the formatters again in the startup in the HttpConfiguration that happened to the unity.

Here is the code for StartUp:

public void Configuration(IAppBuilder app)
        {
            HttpConfiguration httpConfig = new HttpConfiguration();
            GlobalConfiguration.Configuration.Formatters.Add(new JsonHalMediaTypeFormatter());
            GlobalConfiguration.Configuration.Formatters.Add(new XmlHalMediaTypeFormatter());
// this twolines to httpConfig add
            httpConfig.Formatters.Add(new JsonHalMediaTypeFormatter());
            httpConfig.Formatters.Add(new XmlHalMediaTypeFormatter());
// owin etcetcetc
            ConfigureWebApi(httpConfig);

            app.UseCors(Microsoft.Owin.Cors.CorsOptions.AllowAll);

            app.UseWebApi(httpConfig);

        }

 private void ConfigureWebApi(HttpConfiguration config)
        {
            config.MapHttpAttributeRoutes();

            var container = Bootstrapper.BuildUnityContainer();
            config.DependencyResolver = new Unity.WebApi.UnityDependencyResolver(container);
        }

I hope this can help someone with the same problem!
Thank you again for everything!

**Comment by kbrichan** [comment]
Hurrah! Good work finding the problem.
An unexpected connection between dependency injection, [Route], and content negotiation.
Thanks.
