### ISSUE TITLE
Asp.net core 2.0 support release

### ISSUE THREAD

**Issue by wgtmpeters** [JakeGinnivan/WebApi.Hal#140]
Hi,

We would like to use the WebApi.Hal package in a .net core MVC application but the latest version (2.6.0) is not Asp.net .core compatible.
In the repository It seems that the sources have been updated to build against netStandard 2.0, do you plan on releasing a new version soon?

regards,
Willem

**Comment by panmanphil** [comment]
You mean a new nuget package right? I have a more fully tested implementation, but wanted to build a net core project in the solution before releasing to complement the existing .net framework solution.

**Comment by wgtmpeters** [comment]
yes I mean a new nuget release

**Comment by panmanphil** [comment]
Would anybody else from the group like to see more before we do a nuget release? Next, I wonder if I'd actually be able to do this 3.0 version to nuget, what sort of permissions I'd run into.

**Comment by kbrichan** [comment]
I've been sort of silent in this group for a while, not because I've gone away -- we're actively using this library every day. The reason for silence is I have confidence in the improvements and the people doing them. I'd say go for it.

**Comment by panmanphil** [comment]
I made a request to Jake via nuget.org to become an owner of the package so i can upload the 3.0 nuget version targeting netstandard2.0. Hopefully the email address associated with the package is still live.

**Comment by panmanphil** [comment]
Last call for @JakeGinnivan before we have to take a more drastic action to get a new nuget package out there. The existing nuget package owners have to approve it, or one of us needs to become an owner or we may have rename the package start over.

**Comment by panmanphil** [comment]
Happy to say that a new nuget package with the .netstandard work from @Jetski5822 has been released to nuget.org. 

https://www.nuget.org/packages/WebApi.Hal/

**Comment by Jetski5822** [comment]
YAY!!!
