### ISSUE TITLE
Self link - limited to one

### ISSUE THREAD

**Issue by romcoudray** [JakeGinnivan/WebApi.Hal#146]
We have some cases where a resource can be reached by its Id or its Code.
The two following routes are then representing the self link:
api/resource/{id}
api/resource/{code}

But it's not possible to have two self links due to the ToLink method of the representation, wich performs a SingleOrDefault link statement to find the self link :

`link = Links.SingleOrDefault(x => x.Rel == "self");`

Would it be possible to use a FirstOrDefault statement instead and thus to allow the definition of 2 (or more) self links for a representation ?

**Comment by vsliouniaev** [comment]
This breaks the spec though. 

It also becomes more difficult to write clients and client libraries I've seen all assume that there's a single self link.

You could add a "search by code" link or allow both id and code to be passed as the parameter.

But most of all I'd consider why it's necessary to identify a resource by two separate unique ids. If it's two separate references between parties, then a search seems appropriate. If the id is just an internal DB representation, then I would consider omitting it entirely

**Comment by romcoudray** [comment]
Ok I see your point. Thanks for the quick answer !
