### ISSUE TITLE
_embedded part is missing for HAL+JSON accept type when user make the call for same API second time and so on

### ISSUE THREAD

**Issue by gittadesushil** [JakeGinnivan/WebApi.Hal#152]
Both the time Expected:

```
{
    "_links": {
        "self": {
            "href": "/api/grocessories/"
        },
        "items": {
            "href": "/api/grocessories/be8032c0-9439-3665-a47e-24b4fc451f19"
        }
    },
    "_embedded": {
        "items": [
            {
                "Id": "be8032c0-9439-3665-a47e-24b4fc451f19",
                "_links": {
                    "self": {
                        "href": "/api/grocessories/be8032c0-9439-3665-a47e-24b4fc451f19"
                    },
                    "itemlines": {
                        "href": "item-lines/3ee15175-1283-3624-8d68-59f7d7208d6f"
                    }
                },
                "_embedded": {
                    "itemlines": [
                        {
                            "Id": "3ee15175-1283-3624-8d68-59f7d7208d6f",
                            "_links": {
                                "self": {
                                    "href": "item-lines/3ee15175-1283-3624-8d68-59f7d7208d6f"
                                }
                            }
                        }
                    ]
                }
            }
        ]
    }
}
```
But Actual (after first call and so on)
```
{
     "_links": {
        "self": {
            "href": "/api/grocessories/"
        },
        "items": {
            "href": "/api/grocessories/be8032c0-9439-3665-a47e-24b4fc451f19"
        }
    },
    "_embedded": {
        "items": [
            {
                "Id": "be8032c0-9439-3665-a47e-24b4fc451f19",
                "_links": {
                    "self": {
                        "href": "/api/grocessories/be8032c0-9439-3665-a47e-24b4fc451f19"
                    },
                    "itemlines": {
                        "href": "item-lines/3ee15175-1283-3624-8d68-59f7d7208d6f"
                    }
                }
            }
        ]
    }
}
```

**Comment by panmanphil** [comment]
I don't recall any specific conversation about how far down the tree the embedded items should go, but I'd not expect them to be there at all. Links can be circular, so if you just kept following the tree, what would prevent an infinite loop? Others could weigh in, but I think not including embedded sections in the _embedded section is by design

**Comment by kbrichan** [comment]
We have models with embedded in embedded. And it works first and second time. I'm not sure why your model isn't working. Perhaps you could share with us your model.

**Comment by gittadesushil** [comment]
> We have models with embedded in embedded. And it works first and second time. I'm not sure why your model isn't working. Perhaps you could share with us your model.

@kbrichan Please find model classes in below gist
https://gist.github.com/gittadesushil/35aedb7c000a49e614962708bd96a956

**Comment by kbrichan** [comment]
Hmmm. I'm not sure what is wrong. Since it is failing for you and you're able to debug, perhaps you could debug a little further to find why it fails the second time. It would not be effective for me to debug because it works for me.

**Comment by gittadesushil** [comment]
> Hmmm. I'm not sure what is wrong. Since it is failing for you and you're able to debug, perhaps you could debug a little further to find why it fails the second time. It would not be effective for me to debug because it works for me.

Yes second time List<EmbeddedResource> get re-initialised and count becomes 0. Means In the first request whatever the structure is there get lost in second request and we can see the different in the first and second response.

@kbrichan Is it possible for you to share your model classes with me? Also what is the version do you have for WebApi.HAL?.

**Comment by kbrichan** [comment]
Are you by any chance caching the instance and reusing the cached instance the second time? The serialization process might be modifying the object in order to perform the hal translations necessary. So if you're reusing the same instance the second time instead of regenerating the object, this might explain what is happening.

**Comment by gittadesushil** [comment]
Yes we are caching the instance.
