### ISSUE TITLE
Generic representations?

### ISSUE THREAD

**Issue by BrianVallelunga** [JakeGinnivan/WebApi.Hal#32]
I'm trying to figure out a method of returning my models that doesn't involved entirely recreating them into a Representation. The simplest thing I can think of is to make Representation into a generic type. This way I could just do:

``` C#
public abstract class Representation<TResource>
{
    public Representation(TResource resource)
    {
        this.Resource = resource;
    }
}

public class PersonRepresentation : Representation<Person>
{
}
```

The vast majority of PersonRepresentation would then use the resource for the fields. In this way I could add additional properties as needed. Obviously I'd need a method of having the representation ignore certain properties as well.

I think this could be done with code similar to AutoMapper's such as:

``` C#
public class PersonRepresentation : Representation<Person>
{
    public PersonRepresentation(Person person)
    {
         this.Resource = person;
         this.CustomizeResource(person => person.Password, options => options.HideFromRepresentation());
    }
}
```

Has there been any thought on pursuing this sort of strategy?

**Comment by panmanphil** [comment]
closing stale issue
