### ISSUE TITLE
CreateUri only supports relative Uris

### ISSUE THREAD

**Issue by ghost** [JakeGinnivan/WebApi.Hal#39]
Currently the CreateUri method only supports creating relative Uris.  If my Uri template isn't relative, an exception is thrown.  It would be nice to be able to handle absolute Uris.

**Comment by vsliouniaev** [comment]
Looks like the fix for this, which uses `VirtualPathUtility.ToAbsolute(href)`, does not actually create absolute URIs, but a relative URI with absolute path. 

See: http://stackoverflow.com/questions/2239405/hateoas-absolute-or-relative-urls
