### ISSUE TITLE
SimpleListRepresentation - Rel issue

### ISSUE THREAD

**Issue by mihaisandulescu** [JakeGinnivan/WebApi.Hal#42]
Hello everyone!

I try to implement a generic class to use the SimpleListRepresentation but I have a little issue with the Rel attribute.
My class looks like this:

public class HalRepresentationList<TResource> : SimpleListRepresentation<TResource> where TResource : IResource 
    {
        public HalRepresentationList(IList<TResource> tasks)
            : base(tasks)
        {
        }

```
    protected override void CreateHypermedia()
    {
        this.Href = "testHref";
        this.Rel = "tasks";
        this.LinkName = "testLinkName";
    }
}
```

When I test its serialization, the _embedded resource does not use correctly (it does not show it) the Rel attribute like in the image below:
![tasks_bad](https://f.cloud.github.com/assets/6784571/2267551/133d7052-9eb9-11e3-9d06-a2f24b1dfd3e.JPG)

It should look like this:

![tasks_good](https://f.cloud.github.com/assets/6784571/2267554/1f9bdef6-9eb9-11e3-8a10-2cc26ba3da93.JPG)

I have to mention that this issue is on the current version on NuGet. I've got the code from github, and it shows "unknownRel-TaskHalRepresentation".
I looked in the code for this, and found out that in the _embedded resource, the Rel attribuite is taken from each resource in the list of resources as the next line speaks:

Embedded = resourceList.Count > 0 ? resourceList.ToLookup(r => r.Rel) : null;

I've changed this line with:

Embedded = resourceList.Count > 0 ? resourceList.ToLookup(r => this.Rel) : null;

and it works.
Is is correct, or I should set the Rel attribuite on each resource in the list of resources in order to get the Rel attribute of the entire list as it should be?

Thank you!
Mihai

**Comment by panmanphil** [comment]
closing stale issue
