### ISSUE TITLE
Dynamic object properties missing!

### ISSUE THREAD

**Issue by mihaisandulescu** [JakeGinnivan/WebApi.Hal#51]
Hello everyone,

I want to be able to add dynamic properties to an object. For example, using a IDictionary<string, string> or even IDictionary<string, object> to be represented as properties of the main object, not as embedded resourses or anything else.
I saw in the code that GetProperties() is used to iterate through the properties of the object to be represented. I've tried to use DLR to dynamically add new properties, but it's quite difficult to achieve it, and must be implemented for every object that we want to have this behaviour.
Maybe using data annotations like:

[RenderAsProperty]
IDictionary<string, string> dynamicProperties;

or

[RenderAsProperty]
IDictionary<string, object> dynamicObjects;

Thank you for your support!
Mihai

**Comment by panmanphil** [comment]
closing stale issue
