### ISSUE TITLE
Resources without self link (or _links)!

### ISSUE THREAD

**Issue by mihaisandulescu** [JakeGinnivan/WebApi.Hal#52]
I want to be able to serialize a resource without the self link (also without the _links). When I don't set the Href attribute, in RepopulateHyperMedia() we have:

if (Links.Count(l=>l.Rel == "self") == 0)
                Links.Insert(0, new Link { Rel = "self", Href = Href });

but the Href is null. Then I get an error - "Value cannot be null. Parameter name: virtualPath" -  in public string ResolveUri(string href) from LinksConverter.cs.

I would test also if the Href is not null as follows:

if (Links.Count(l=>l.Rel == "self") == 0 && Href != null)
                Links.Insert(0, new Link { Rel = "self", Href = Href });

Acording to hal-json specification:

4.1.1.  _links
   The reserved "_links" property is OPTIONAL.

Does it makes sense to you also?
Thank you!

**Comment by panmanphil** [comment]
closing stale issue
