### ISSUE TITLE
lowerCamelCase for Resource Properties

### ISSUE THREAD

**Issue by AlexZeitler** [JakeGinnivan/WebApi.Hal#54]
Is there a way to enable lowerCamelCase for Resource Properties?

The only way I found to enable it, was modifying the ResourceConverter [here](https://github.com/JakeGinnivan/WebApi.Hal/blob/master/WebApi.Hal/JsonConverters/ResourceConverter.cs#L33) and add this line of code:

`serializer.ContractResolver = new CamelCasePropertyNamesContractResolver();`

This would ease the usage when dealing with JavaScript-Clients.
The [specification](http://stateless.co/hal_specification.html) also uses lowerCamelCase as well as the [HAL Browser](http://haltalk.herokuapp.com) does.

Another option would be to introduce a property `SerializerSettings` for the `ResourceConverter` which would allow the user of WebApi.Hal to decide itself which casing he prefers.

The `JsonHalMediaTypeFormatter` then also must be aware of this property and maybe could expose a property `ResourceConverterSerializerSettings`.

**Comment by panmanphil** [comment]
closing stale issue
