### ISSUE TITLE
Serialization of one-item SimpleListRepresentation

### ISSUE THREAD

**Issue by tompetko** [JakeGinnivan/WebApi.Hal#56]
Hi there,

I'd like to ask, why is desired to serialize one item SimpleListRepresentation collection as object and not as array? Programmer knows, that resulting data are array type and the count can not change format from array to object.

**Comment by GraemeF** [comment]
> Also with no items it should be an empty array.

It looks like an empty list is being skipped during serialization, so it doesn't appear in the representation at all. Is this some JSON formatting setting I have wrong, or still something that needs changing in WebApi.Hal itself?

**Comment by GraemeF** [comment]
Looks like this PR addresses this issue: https://github.com/JamesNK/Newtonsoft.Json/pull/601
