### ISSUE TITLE
pull request #59 broke a unit test for single vs. array embedded object

### ISSUE THREAD

**Issue by kbrichan** [JakeGinnivan/WebApi.Hal#63]
Pull request #59 fixed emitting an embedded array as an array regardless if the array contains just a single element. However, the fix caused ALL embedded objects to get emitted as an array, even for the case where an embedded object property is declared as a single instance. There was an existing unit test for this situation, which now fails.

I discovered this when running the unit tests for the unrelated work I'm now doing on fixing some link problems. I'll fix this array problem now, too, while I'm at it.

**Comment by panmanphil** [comment]
closing stale issue
