### ISSUE TITLE
Attribute to override rel as convenience for serializing and for disambiguating deserialization

### ISSUE THREAD

**Issue by kbrichan** [JakeGinnivan/WebApi.Hal#67]
Let's enhance this project to allow attributing embedded properties with a rel override, such as this:

```
public class AuthorRepresentation : Representation {
   [Rel("recentPosts")]
   public List<PostResource> RctPosts { get; set; }
   [Rel("popularPosts")]
   public List<PostResource> PopPosts { get; set; }
}
```

The net result is to output json like this:

```
{
    "_embedded": {
        "recentPosts": [
            {"someProp1": "someValue1"},
            {"someProp1": "someValue2"}
        ],
        "popularPosts": [
            {"someProp1": "someValue3"},
            {"someProp1": "someValue4"}
        ]
    }
}
```

The common thing currently is to just have PostResource hardcode its rel to something. So to accomplish the above json with the current implementation without the Rel override attribute, one would have to set the rel of each of the objects in the RctPost list to one rel and the objects in PopPosts to another.

Also, upon deserializing, without the Rel override attribute, the deserializer would have no idea which list to put the incoming PostResource objects into.

**Comment by panmanphil** [comment]
closing stale issue
