### ISSUE TITLE
curie, profile and type support

### ISSUE THREAD

**Issue by panmanphil** [JakeGinnivan/WebApi.Hal#74]
There are some pretty key link attributes missing from Link. Of these curies are the most important. If you state a rel, a name that describes what happens, why you are doing it, when you follow a link, it must be one of:
- IANA registered link relation, can be listed as plain text
- a full URI, in essence a URL that points to a specific document
- a "namespaced" aka curie link of the form <curie name>:<relation name> where the curie name will refer to a link to a document to be used as a link relation extension. Look at the hypertalk sample application for a simple working example. 

profile refers to an IRI, again essentially a URL pointing to a profile document that explains what the data at the end of the link is. iCal would be an example of a profile. 

the type attribute allows the link to be a different media type. Since the operating premise for doing forms with HAL, still the subject of intense debate, is to use HTML, having a link that says type="text/html" allows your application/hal+json to say follow this link and get html. 

i am working on a pull request, but may need help with round tripping the curies

**Comment by mxrss** [comment]
How do you use curie links? I keep trying to add curie links and get exceptions thrown.

**Comment by panmanphil** [comment]
closing stale issue
