### ISSUE TITLE
a solution to remind people to use accept header of application/hal+json

### ISSUE THREAD

**Issue by kbrichan** [JakeGinnivan/WebApi.Hal#79]
People regularly report bugs, thinking this library isn't working, only to find out they forgot the accept header. How about if we help them a bit in the ordinary JSON response? We could put a const string in the Representation class which only gets serialized to JSON, not hal+json. It could read something like:
"hey": "you're using the webapi.hal library but you're not using the accept header to get hal+json; so this object is ordinary JSON, not hal+json"

**Comment by panmanphil** [comment]
closing stale issue
