### ISSUE TITLE
Attribute/Reflection for Link Generation

### ISSUE THREAD

**Issue by chrisaswain** [JakeGinnivan/WebApi.Hal#81]
Have you thought about creating an attribute that could be added to properties on Representation objects to have links autogenerated for those object properties?

Maybe something like a LinkAttribute that can be applied multiple times to properties on Representation objects that should have Links generated for them?  Just a thought, but it might make it easier to figure out which sub-objects on your DTO's/Representations will have links of their own.  

Example:

public class User
{
    public string Name { get; set; }

```
[Link("addresses", "~/addresses{?page}")]
[Link("address", "~/addresses/{addressId}")]
publict List<Address> Addresses { get; set; }
```

}

Then the base Representation object in the CreateHypermedia() method could use some reflection to find all the LinkAttributes on properties in the object and add to the Links collection.

**Comment by vRITHNER** [comment]
I saw your branch doing part of this but it could be cool to have it for Representation and not only for the ResourceList
The down side of the attribute is we're forced to pass the link as string rather than LinkedTemplate.Beers.Href ....

**Comment by panmanphil** [comment]
closing stale issue
