### ISSUE TITLE
Customize the Rel for an Embedded List

### ISSUE THREAD

**Issue by chrisaswain** [JakeGinnivan/WebApi.Hal#82]
By default, it looks like the EmbeddedResourceConverter is setting the property name for the collection to the Rel value of the first IResource in the list of resources.  But, there are many cases where you may have an embedded resource on your object that represents a list of other resources, but you want to control the name of that list.  

For example, given a list of BeerRepresentations, you may want to call the list beers: [...] rather than the default which is just beer: [...].

**Comment by richardszalay** [comment]
Did a PR for this ever get made?

**Comment by panmanphil** [comment]
Yeah, I remember seeing it. Meanwhile must ... finish ... this .... project ....!

**Comment by panmanphil** [comment]
closing stale issue
