### ISSUE TITLE
Refactor into server + portable client libraries

### ISSUE THREAD

**Issue by glennblock** [JakeGinnivan/WebApi.Hal#85]
Currently the libaries depend on Web API. This kills it for client consumption scenarios.

For my collection+json [libary](https://github.com/WebApiContrib/CollectionJson.Net) I refactored into a core, client and server library. The client library depends on Web API's client library but not the server. It and core are portable thus allowing useage in clients  and Xamarin.

**Comment by panmanphil** [comment]
closing stale issue
