### ISSUE TITLE
3.0 Suggestion

### ISSUE THREAD

**Issue by chrisaswain** [JakeGinnivan/WebApi.Hal#86]
For a 2.0 version of WebApi.Hal, I was thinking we might want to redesign it so your DTO's don't have to inherit from anything, but instead use a combination of attributes and a Representation wrapper object.  That way serialization can be done based on the Accept header value.  If the Accept header 
is just application/json, then only the DTO is serialized.  If the Accept header is applicaton/hal+json, then the framework would use the wrapper + attributes to generate the DTO + the HAL elements.  This would make the framework extensable so that other hypermedia standards like Collection+JSON or Siren could be plugged in as the framework matures and the community begins to contribute new formatters.  In fact, the 2.0 version of the framework could be renamed WebApi.Hypermedia and start out with default support for HAL with more hypermedia standards support to come later.

**Comment by panmanphil** [comment]
closing stale issue
