### ISSUE TITLE
General Hypermedia Theory Question

### ISSUE THREAD

**Issue by chrisaswain** [JakeGinnivan/WebApi.Hal#88]
I know this question is not specifically about WebApi.Hal, but I wanted to ask it here since you guys have extensive experience working with both ASP.NET Web Api and Hypermedia formats (particularly HAL).  

For the sake of discussion, say I have the following classes:

``` C#
        public class Employee
        {
            public string Name { get; set; }
            public List<Address> Addresses { get; set; }
            public Manager Boss { get; set; }
        }
        public class Address
        {
            public string Street { get; set; }
            public string City { get; set; }
            public string Zip { get; set; }
        }
        public class Manager : Employee
        {
            public List<Employee> DirectReports { get; set; }
        }
    }
```

And we have a controller action of:

/Employees/1

Now, I want to configure `Employee`, `Address`, `List<Address>`, and `Manager` with some default metadata (Links).  This would mean that I somehow define the default links for each of those "Types" in my Web Api configuration (probably similar to the way Appenders are done in WebApi.Hal).  

Then, in my controller action, have an `Employee` object I want to return with nested `Addresses` and `Manager` objects.  And, for this particular controller action, I want to add or modify the metadata for not only the `Employee`, but also for the `List<Address>` and `Manager` properties.  

Now, let's say the approach I want to take is to wrap the `Employee` object in some sort of Metadata container object (a `HypermediaObject`) that will auto-populate the Links metadata for the `Employee` instance using the configuration mentioned above, and I also want to be able to add/modify the Links metadata from within the controller action.  

Later in the pipeline, the Formatter and Converters will use the `HypermediaObject` wrapper with it's metadata to serialize the encapsulated `Employee` object using the Links metadata.

Doing this just for the `Employee` object seems pretty straight forward.  Where it gets complicated is when trying to take into account the nested objects (`Address`, `List<Address>` , and `Manager`).  It seems like you would want to somehow wrap those nested objects in their own `HypermediaObject` containers with their own default metadata, while still allowing for controller action customizing.  

Hopefully this hypothetical scenario makes sense.  For the sake of theoretical discussion:

**Does this approach seem alright?**
**If so, how should you overcome the problem of nested properties that also need metadata?**
### Note: The problem I'm trying to solve here is:
1. I want to be able to return just a plain old DTO from my controller action. 
2. I want to have some default metadata configured that is associated with my DTO.
3. I want to be able to add/modify the metadata associated with my DTO contextually in my controller action.  
4. I want to be able to plug-in different Formatters to support different Hypermedia formats over time.
5. I only want to return hypermedia format (with metadata) if the Accept header matches a registered formatter.  Otherwise, I want the plain old DTO returned.  

A custom `ActionFilterAttribute` can solve # 1 by intercepting the Request and replacing it with a `HypermediaObject`.

A configuration registration mechanism similar to the appenders in WebApi.Hal can solve # 2.

Storing extra Links metadata in the `Request.Properties` (made easier with extension methods) can solve # 3.  Then, the custom `ActionFilterAttribute` can merge the default metadata with the contextual metadata from the Request when it wraps the DTO in the `HypermediaObject`.

By keeping the metadata fairly generic and not tying it directly to HAL, we can support # 4.  

By checking the Accept header inside the custom `ActionFilterAttribute`, we can support # 5.

**Comment by panmanphil** [comment]
closing stale issue
