### ISSUE TITLE
Question: What is the purpose of HalJsonConverterContext?

### ISSUE THREAD

**Issue by mihaisandulescu** [JakeGinnivan/WebApi.Hal#93]
Hello all,

I want to use the 2.5.0 version but I'm getting nowhere. My problem is that, in Representation.cs, the if (!ResourceConverter.IsResourceConverterContext(context)) is always true, so no other code is executed. Can you explain me the purpose of HalJsonConverterContext and how it should be used? (I was using the old 2.1.0.14 version)

**Comment by Dunken** [comment]
Do you use media type application/json instead of application/json+hal?

**Comment by mihaisandulescu** [comment]
I didn't add the application/hal+json header. Thanks Dunken!

**Comment by panmanphil** [comment]
closing stale issue
