### ISSUE TITLE
Question: get list of links even if accept header is NOT hal+json

### ISSUE THREAD

**Issue by Dunken** [JakeGinnivan/WebApi.Hal#95]
In version 1 I got the list of links filled even if the accept header was just json (instead of hal+json). In version 2.5 it seems to be different (_links is present but always empty)... Can I go back to the version 1 behavior?

**Comment by Dunken** [comment]
Hmm, it was a nice bug ;-)

I didn't want to introduce HAL yet but still take advantage of all the _links (I simply documented _links) and all the amenities the library provides. The embedded resources got embedded without the _embedded layer but as plain json-lists...

If I replace the json-formatter I also get the _embedded layer though...

**Comment by panmanphil** [comment]
closing stale issue
