### ISSUE TITLE
XmlHalMediaTypeFormatter cannot be used as the default XML serializer

### ISSUE THREAD

**Issue by Karamell** [JakeGinnivan/WebApi.Hal#96]
The JsonFormatter can be used as the default JsonFormatter:
`GlobalConfiguration.Configuration.Formatters.JsonFormatter`
if I add it like so: 
`GlobalConfiguration.Configuration.Formatters.Insert(0, new JsonHalMediaTypeFormatter());`

It would be convinent to be able to do the same with the `XmlHalMediaTypeFormatter` like so:
`GlobalConfiguration.Configuration.Formatters.Insert(0, new XmlHalMediaTypeFormatter());`
but the `GlobalConfiguration.Configuration.Formatters.XmlFormatter` stays the same. Is it possible to change this?

**Comment by justinyoo** [comment]
Before adding both formatters, it would be a good idea to clear existing formatters by:

```
GlobalConfiguration.Configuration.Formatters.Clear()
```

Then just simply add both, not insert them.

**Comment by panmanphil** [comment]
closing stale issue
