### ISSUE TITLE
Returning Http Status Codes

### ISSUE THREAD

**Issue by karaaie** [JakeGinnivan/WebApi.Hal#97]
Hello! 
Really neat work you guys have here!

My question is regarding returning http status codes.
Say that I have a controller with a action like this:

```
public SessionRepresentation Post(string username, string password){
   // try to login user
   var user  = UserRepository.Login(username, password)   
   if(user == null){
        /// Return status code 404 because the user doesnt exist.
        return ?
   }


   return new SessionRepresentation{
    // Hal stuff.. 
  }
}
```

How do I return status codes? `NotFound()` doesnt work because it clashes with the SessionRepresentation type.

**Comment by karaaie** [comment]
Hm.. after a bit of digging I think I found my answer.. not very pretty but will probably have to do.
http://www.asp.net/web-api/overview/error-handling/exception-handling

**Comment by wis3guy** [comment]
yup, that is how i do it myself as well ...

Ciao,
Geoffrey

--
Geoffrey Braaf | +31655793290
Freelance .NET Software Architect & Passionate Developer |
http://wis3guy.net
Findsi: find-as-i | http://www.findsi.com

**Comment by tgitchel** [comment]
This is the way I do it in Web API 2.2:

public IHttpActionResult Post(string username, string password){
   // try to login user
   var user  = UserRepository.Login(username, password)   
   if(user == null){
        /// Return status code 404 because the user doesnt exist.
        return NotFound("Optional message here");
   }


   var session = new SessionRepresentation{
    // Hal stuff.. 
  }
  // Return status code 200 with Representation object
  return Ok(session);
}

**Comment by panmanphil** [comment]
closing stale issue
