### ISSUE TITLE
Problem when a resource has no links

### ISSUE THREAD

**Issue by mihaisandulescu** [JakeGinnivan/WebApi.Hal#98]
When having a resource without any link (no href also as described in the issue #52), we get a NULL exception because of the line:

curies.AddRange(Links.Where(l => l.Curie != null).Select(l => l.Curie));

in Representation.cs - line 126.
I think we should test if any value in the Links list and then use the Select method.

Thank you!

**Comment by wis3guy** [comment]
I agree that a check would be a graceful solution, and should definately be implemented (pull request?), but your resources **should** at least have a self link. It **must** not, but it is recommended.

~~~
8.1.  Self Link

Each Resource Object SHOULD contain a 'self' link that corresponds
with the IANA registered 'self' relation (as defined by [RFC5988])
whose target is the resource's URI.
~~~

https://tools.ietf.org/html/draft-kelly-json-hal-06#section-8.1

**Comment by mihaisandulescu** [comment]
I agree with you that a resource should have at least a self link, but there might be situations where, for example, in the embedded resource list, for each embedded resource you want to block the navigation to it, so the links must not be showed.

**Comment by wis3guy** [comment]
I'm of course not an authority on the subject, but i'd say that if you embed resources, you embed it as a proper resource, including the recommended links. Why would you block your clients from navigating to a certain resource.

I'd personally recommend adding such objects to the representation as state properties, not as embedded resources.

**Comment by wis3guy** [comment]
I just ran into a situation where i want to generate a response without a self link, namely an error response. Will create a pull request in the near future ...

**Comment by dave-kennedy** [comment]
I'm running into this problem too, except it only happens when the serialized HAL object contains a list of HAL child objects and the children don't have links. e.g.

```c#
public class ParentHalObject : Representation
{
    public string AProperty { get; set; }
    public IList<ChildHalObject> Children { get; set; }
}

public class ChildHalObject : Representation
{
    public string AnotherProperty { get; set; }
}
```

The problem occurs when an instance of this class is serialized. I was able to pause the debugger right before it with some strange results:

![image](https://cloud.githubusercontent.com/assets/13735532/10382152/50e936f2-6dde-11e5-870e-120680578585.png)

Apparently the Link list contains a null item o_O

**Comment by wis3guy** [comment]
i will look into this tomorrow and see if i can create a pull request to fix this.

**Comment by panmanphil** [comment]
closing stale issue
